"""The quiet sweep: transcript reading, watermarks, extraction gates, offers."""

import importlib.machinery
import importlib.util
import json
from pathlib import Path

CORE = Path(__file__).resolve().parents[1] / "bin" / "core"


def load_core():
    l = importlib.machinery.SourceFileLoader("core", str(CORE))
    m = importlib.util.module_from_spec(importlib.util.spec_from_loader("core", l))
    l.exec_module(m)
    return m


def write_transcript(path, entries):
    path.write_text("".join(json.dumps(e) + "\n" for e in entries))
    return path


def user(text, **kw):
    return dict({"type": "user", "message": {"role": "user", "content": text}, "timestamp": "2026-10-01T10:00:00Z"}, **kw)


def assistant(*blocks, **kw):
    return dict({"type": "assistant", "message": {"role": "assistant", "content": list(blocks)},
                 "timestamp": "2026-10-01T10:00:05Z"}, **kw)


def test_turns_keep_only_the_conversation(tmp_path):
    core = load_core()
    t = write_transcript(tmp_path / "s.jsonl", [
        {"type": "mode", "mode": "x"},
        user("<local-command-caveat>Caveat: generated by local commands</local-command-caveat>"),
        user("let's use SQLite, Postgres is overkill here"),
        assistant({"type": "thinking", "thinking": "secret reasoning"},
                  {"type": "text", "text": "Agreed, SQLite it is."},
                  {"type": "tool_use", "name": "Bash", "input": {"command": "ls"}}),
        user([{"type": "tool_result", "content": "file listing"}]),
        user("meta injection", isMeta=True),
        user("subagent prompt", isSidechain=True),
        assistant({"type": "text", "text": "Done."}),
        user([{"type": "text", "text": "no, never use emoji in commits"}]),
    ])
    turns = core.transcript_turns(t)
    assert [(r, x) for _, r, x in turns] == [
        ("user", "let's use SQLite, Postgres is overkill here"),
        ("assistant", "Agreed, SQLite it is.\nDone."),
        ("user", "no, never use emoji in commits"),
    ]
    assert turns[0][0] == 3  # line number in the transcript, for traceable quotes


def test_turns_survive_garbage_lines(tmp_path):
    core = load_core()
    t = tmp_path / "s.jsonl"
    t.write_text('not json\n{"type": "user"}\n' + json.dumps(user("real message")) + "\n")
    assert [x for _, _, x in core.transcript_turns(t)] == ["real message"]


def test_hook_injected_context_is_not_the_person(tmp_path):
    core = load_core()
    t = write_transcript(tmp_path / "s.jsonl", [
        user("<system-reminder>recall lines</system-reminder>"),
        user("<command-name>/clear</command-name>"),
        user("Another Claude session sent a message: report"),
        user("ship it on thursday"),
    ])
    assert [x for _, _, x in core.transcript_turns(t)] == ["ship it on thursday"]


TURNS = [(3, "user", "let's use SQLite, Postgres is overkill here"),
         (4, "assistant", "Agreed. Should we also add Redis?"),
         (7, "user", "maybe we could add Redis later, not sure"),
         (9, "user", "no, never use emoji in commits")]


def test_gate_keeps_only_verbatim_quotes_from_the_person():
    core = load_core()
    items = [
        {"type": "decision", "statement": "Logan chose SQLite over Postgres.", "quote": "let's use SQLite", "line": 3},
        {"type": "decision", "statement": "Redis will be added.", "quote": "Should we also add Redis?", "line": 4},  # assistant's words
        {"type": "decision", "statement": "Logan chose MySQL.", "quote": "let's use MySQL", "line": 3},  # not said
        {"type": "correction", "statement": "Never use emoji in commit messages.", "quote": "never use emoji in  commits", "line": 9},
    ]
    kept = core.sweep_gate(items, TURNS)
    assert [k["statement"] for k in kept] == ["Logan chose SQLite over Postgres.", "Never use emoji in commit messages."]
    assert kept[1]["line"] == 9  # line comes from where the quote really is


def test_gate_drops_hypotheticals_and_questions():
    # "He didn't say no" is not "he said yes": a maybe is never a decision.
    core = load_core()
    items = [{"type": "decision", "statement": "Redis will be added later.", "quote": "maybe we could add Redis later", "line": 7}]
    assert core.sweep_gate(items, TURNS) == []


def test_gate_drops_unknown_types_and_empty_statements():
    core = load_core()
    items = [{"type": "vibe", "statement": "x", "quote": "let's use SQLite", "line": 3},
             {"type": "decision", "statement": " ", "quote": "let's use SQLite", "line": 3},
             "garbage", {"type": "decision"}]
    assert core.sweep_gate(items, TURNS) == []


def test_gate_dedupes_the_same_quote():
    core = load_core()
    item = {"type": "decision", "statement": "SQLite.", "quote": "let's use SQLite", "line": 3}
    assert len(core.sweep_gate([item, dict(item, statement="SQLite chosen.")], TURNS)) == 1


# ---- core sweep: quiet window, watermarks, offers ----
import os
import subprocess
import threading
import time
from http.server import BaseHTTPRequestHandler, HTTPServer

import pytest


class FakeChat(BaseHTTPRequestHandler):
    reply = {"items": []}
    calls = []
    fail = False

    def do_POST(self):
        body = json.loads(self.rfile.read(int(self.headers["Content-Length"])))
        FakeChat.calls.append(body)
        if FakeChat.fail:
            self.send_response(500); self.end_headers(); return
        out = json.dumps({"message": {"role": "assistant", "content": json.dumps(FakeChat.reply)}}).encode()
        self.send_response(200); self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(out))); self.end_headers(); self.wfile.write(out)

    def log_message(self, *a):
        pass


@pytest.fixture
def chat():
    FakeChat.reply, FakeChat.calls, FakeChat.fail = {"items": []}, [], False
    srv = HTTPServer(("127.0.0.1", 0), FakeChat)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    yield "http://127.0.0.1:{}".format(srv.server_port)
    srv.shutdown()


def setup_sweep(tmp_path, url, quiet_ago=3600):
    home = tmp_path / "home"
    proj = home / ".claude" / "projects" / "-x"
    proj.mkdir(parents=True)
    t = write_transcript(proj / "sess.jsonl", [
        user("let's use SQLite, Postgres is overkill here"),
        assistant({"type": "text", "text": "Agreed."}),
        user("and never use emoji in commit messages"),
        assistant({"type": "text", "text": "Noted."}),
    ])
    old = time.time() - quiet_ago
    os.utime(str(t), (old, old))
    h = tmp_path / "corehome"
    h.mkdir()
    (h / "recall.conf").write_text("sweep_model fake-llm\nsweep_url {}\n".format(url))
    return t


def run_core(tmp_path, *args):
    env = {"HOME": str(tmp_path / "home"), "CORE_HOME": str(tmp_path / "corehome"), "PATH": os.environ["PATH"]}
    return subprocess.run(["python3", str(CORE), *args], capture_output=True, text=True, env=env, timeout=60)


def test_sweep_offers_items_with_provenance_and_never_writes_memory(chat, tmp_path):
    t = setup_sweep(tmp_path, chat)
    FakeChat.reply = {"items": [{"type": "correction", "statement": "Never use emoji in commit messages.",
                                 "quote": "never use emoji in commit messages", "line": 99}]}
    r = run_core(tmp_path, "sweep")
    assert r.returncode == 0, r.stderr
    inbox = run_core(tmp_path, "inbox").stdout
    assert "Never use emoji in commit messages." in inbox
    assert "never use emoji in commit messages" in inbox and "sess.jsonl:3" in inbox  # real line
    assert not list((tmp_path / "home" / ".claude").rglob("*.md"))  # an offer, not a write


def test_sweep_reads_each_part_once(chat, tmp_path):
    t = setup_sweep(tmp_path, chat)
    run_core(tmp_path, "sweep")
    run_core(tmp_path, "sweep")
    assert len(FakeChat.calls) == 1
    with open(str(t), "a") as fh:  # new conversation later
        fh.write(json.dumps(user("remind me to renew the domain on friday")) + "\n")
        fh.write(json.dumps(user("and the cert too")) + "\n")
    old = time.time() - 3600
    os.utime(str(t), (old, old))
    run_core(tmp_path, "sweep")
    assert len(FakeChat.calls) == 2
    sent = FakeChat.calls[1]["messages"][0]["content"]
    assert "renew the domain" in sent and "SQLite" not in sent  # only the new part


def test_sweep_waits_for_a_quiet_conversation(chat, tmp_path):
    setup_sweep(tmp_path, chat, quiet_ago=60)  # still active a minute ago
    run_core(tmp_path, "sweep")
    assert FakeChat.calls == []


def test_sweep_model_down_keeps_watermark_and_fails_loudly(chat, tmp_path):
    setup_sweep(tmp_path, chat)
    FakeChat.fail = True
    r = run_core(tmp_path, "sweep")
    assert r.returncode == 1 and "couldn't" in (r.stdout + r.stderr)
    FakeChat.fail = False
    run_core(tmp_path, "sweep")
    assert len(FakeChat.calls) == 2  # retried the same part, nothing lost


def test_sweep_without_model_explains_setup(tmp_path):
    (tmp_path / "corehome").mkdir()
    r = run_core(tmp_path, "sweep")
    assert r.returncode == 2 and "sweep_model" in r.stderr


def test_same_offer_is_not_repeated(chat, tmp_path):
    t = setup_sweep(tmp_path, chat)
    FakeChat.reply = {"items": [{"type": "decision", "statement": "SQLite over Postgres.",
                                 "quote": "let's use SQLite", "line": 1}]}
    run_core(tmp_path, "sweep")
    os.unlink(str(tmp_path / "corehome" / "sweep-state.json"))  # force a re-read of the same part
    run_core(tmp_path, "sweep")
    assert run_core(tmp_path, "inbox").stdout.count("SQLite over Postgres.") == 1


def test_custom_sweep_dir_with_tilde(chat, tmp_path):
    t = setup_sweep(tmp_path, chat)
    other = tmp_path / "home" / "elsewhere" / "-p"
    other.mkdir(parents=True)
    os.replace(str(t), str(other / "sess.jsonl"))
    old = time.time() - 3600
    os.utime(str(other / "sess.jsonl"), (old, old))
    with open(str(tmp_path / "corehome" / "recall.conf"), "a") as fh:
        fh.write("sweep_dir ~/elsewhere\n")
    r = run_core(tmp_path, "sweep")
    assert r.returncode == 0, r.stderr
    assert len(FakeChat.calls) == 1


def test_gate_accepts_a_tidied_quote_but_keeps_the_persons_exact_words():
    core = load_core()
    turns = [(5, "user", "I want you to pursue it in off hours to maximise my effeciency, one of those would be Poker Coach")]
    items = [{"type": "preference", "statement": "Run token-heavy work off-hours.",
              "quote": "I want you to pursue it in off hours to maximize my efficiency", "line": 1}]
    kept = core.sweep_gate(items, turns)
    assert len(kept) == 1 and kept[0]["line"] == 5
    assert kept[0]["quote"] in turns[0][2]  # evidence is what he typed, typos and all


def test_gate_rejects_a_fabricated_quote():
    core = load_core()
    turns = [(5, "user", "I want you to pursue it in off hours to maximise my effeciency")]
    items = [{"type": "decision", "statement": "x", "quote": "I never want you to work off hours on anything", "line": 5}]
    assert core.sweep_gate(items, turns) == []


def test_a_directive_phrased_as_a_question_is_kept():
    core = load_core()
    turns = [(8, "user", "on mobile, this quote should take over the whole screen? Why is it so tiny?")]
    items = [{"type": "correction", "statement": "On mobile the quote should fill the screen.",
              "quote": "on mobile, this quote should take over the whole screen?", "line": 8}]
    assert len(core.sweep_gate(items, turns)) == 1
